### ISSUE TITLE
Please provide a requirements.txt

### ISSUE THREAD

**Issue by pietsch** [hnez/CoronaWannApp#1]
I managed to get this script running on Debian 10 after installing a fresh version of `protobuf`.

Since I migrated to Debian 11, it refuses to start because some crypto module is missing:
```
$ python3 -i coronawann.py
Traceback (most recent call last):
  File "/home/user/git/CoronaWannApp/coronawann.py", line 27, in <module>
    from Crypto.Protocol.KDF import HKDF
ModuleNotFoundError: No module named 'Crypto'
```

Doing `sudo pip3 install Crypto` or `sudo apt install python3-hkdf` does not help.

I realize that this software is not targeted at end users. However, providing a `requirements.txt` that lists known-to-work versions of the required Python libraries seems like a good idea.

Also, please warn in `README.md` that the step `cw.update_diagnosis_keys()` can take a day or two.

**Comment by hnez** [comment]
Oh, hey there!

I did not expect anyone to actually try using this script. Putting it on GitHub was more of a way to make sure **I** could find it again in a few month time, but I am glad to have another user!

I tend to avoid dealing with python dependencies and just use whatever my Linux distribution provides, but the `requirements.txt` should now include the versions my distribution currently ships.

Putting the database file in RAM, e.g. by running the script in `/tmp` speeds up the key import a lot. This is likely an issue in the way I am using `sqlite3`, that I could not be bothered to fix yet. I've added a note regarding this issue to the `README.md`.

Stay safe
Leonard
